image: docker:latest
services:
    - docker:19.03.5-dind


variables:
  DOCKER_DRIVER: overlay

stages:
  - build

docker-build:
  stage: build
  script:
  - docker login --username=jhmckay93 -p=riverservice1037
  - docker pull jhmckay93/riverservice:latest || true
  - docker build --cache-from jhmckay93/riverservice:latest --tag jhmckay93/riverservice --iidfile imageid.txt .
  - docker push jhmckay93/riverservice
