image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

docker-build:
  stage: build
  script:
  - docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
  - docker pull registry.heroku.com/riverservice/web || true
  - docker build --cache-from registry.heroku.com/riverservice/web --tag registry.gitlab.com/jameshmckay/riverservice --iidfile imageid.txt .
  - docker push registry.gitlab.com/jameshmckay/riverservice
  - apk add --no-cache curl
  - |-